#!/usr/bin/env bash
#Install nginx

apt-get update
apt-get install -y nginx
apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat <<EOT > /etc/haproxy/haproxy.cfg
backend questionTwo
    balance roundrobin
    server 5584-web-01 15.188.232.6:80 check
    server 5584-web-02 35.180.90.107:80 check
EOT
sudo service haproxy restart